@startuml
title Flow_RefreshToken
hide footbox

participant "**Client(curl cmd)**\n\nClientId = 123456\nClientSecret = abcdef" as Client
participant "**AuthorizationServer**\n\nTokenEndpoint\nhttp://localhost:11625/OAuth/Token" as AuthorizationServer
participant "**ResourceServer**\n\nWebAPI\nhttp://localhost:38385/api/Test" as ResourceServer

group アクセストークン取得
    Client -> AuthorizationServer:POST\nhttp://localhost:11625/OAuth/Token\nAuthorization:Basic Base64({ClientId}:{ClientSecret})\n**grant_type=password**\n&username={ユーザーID}\n&password={パスワード}\n&scope={スコープ群}

    note over AuthorizationServer : ClientId,Secretの検証\n - ValidateClientAuthentication()
    note over AuthorizationServer : ユーザーID,パスワードの検証と\nClaimsIdentity（アクセストークン）の生成\n - GrantResourceOwnerCredentials()
    note over AuthorizationServer : **★リフレッシュトークンの生成★**\n - CreateRefreshToken()

    Client <- AuthorizationServer: アクセストークン & **★リフレッシュトークン★**
end group

group アクセストークン再取得
    Client -> AuthorizationServer:POST\nhttp://localhost:11625/OAuth/Token\nAuthorization:Basic Base64({ClientId}:{ClientSecret})\n**grant_type=refresh_token**\n&refresh_token={リフレッシュトークン}

    note over AuthorizationServer : ClientId,Secretの検証\n - ValidateClientAuthentication()
    note over AuthorizationServer : **★リフレッシュトークン受信処理★**\n - ReceiveRefreshToken()
    note over AuthorizationServer : **リフレッシュトークンの生成**\n - CreateRefreshToken()

    Client <- AuthorizationServer: **新しいアクセストークン**\n**& 新しいリフレッシュトークン**

end group

@enduml
