@startuml
title Flow_ClientCredentialGrant
hide footbox

participant "**ClientCredentialGrant.exe**\n\nClientId = 123456\nClientSecret = abcdef" as ClientCredentialGrant
participant "**AuthorizationServer**\n\nTokenEndpoint\nhttp://localhost:11625/OAuth/Token" as AuthorizationServer
participant "**ResourceServer**\n\nWebAPI\nhttp://localhost:38385/api/Me" as ResourceServer

note over ClientCredentialGrant : ◆START◆
group Token取得
    note over ClientCredentialGrant : Program.RequestToken()

    ClientCredentialGrant -> AuthorizationServer:POST\nhttp://localhost:11625/OAuth/Token\nAuthorization:Basic Base64([ClientId]:[ClientSecret])\n**grant_type=client_credentials**

    note over AuthorizationServer : ClientId,Secretの検証\n - ValidateClientAuthentication()
    note over AuthorizationServer : ClaimsIdentityの生成\n - GrantClientCredetails()
    note over AuthorizationServer : AccessTokenの生成\n - OWINが勝手にやる

    ClientCredentialGrant <- AuthorizationServer: AccessToken
end group

group Resource取得
    note over ClientCredentialGrant : Program.AccessProtectedResource()

    ClientCredentialGrant -> ResourceServer: GET\n http://localhost:38385/api/Me\n Authorization:Bearer [AccessToken]
  
    note over ResourceServer:AccessTokenの検証\n - MeController.Get()の[Authorize]属性\n - 検証処理はOWINが勝手にやる
    note over ResourceServer:クライアントに返却する値\n - MeController.User.Identity.Name

    ClientCredentialGrant <-- ResourceServer: Response=123456
    
end group
note over ClientCredentialGrant : ◆END◆

@enduml
